# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
## Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.



import numpy as np
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10], 
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
arr[3] = [1,1,1,1,1]
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 1  1  1  1  1]
 [21 22 23 24 25]]


In [43]:
## Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0


import numpy as np
arr = np.arange(1,17).reshape(4,4)
arr[np.arange(4),np.arange(4)]= [0,0,0,0]
print(arr)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [ ]:
## 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


import numpy as np
arr = np.arange(1,37).reshape(6,6)
sub =arr[3:5,:]
sub1 = arr[:,2:4]
print(sub)
print(sub1)

[[19 20 21 22 23 24]
 [25 26 27 28 29 30]]
[[ 3  4]
 [ 9 10]
 [15 16]
 [21 22]
 [27 28]
 [33 34]]


In [55]:
## 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

import numpy as np
arr = np.arange(1,26).reshape(5,5)
sub =arr[0:4,:]
print(sub)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
## 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.



import numpy as np
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12]) 

print("Addition:", arr1 + arr2)

## Element Wise Subtraction 
print("Subtraction:", arr1 - arr2)
## Element Wise multiplication 
print("Multiplication:", arr1 * arr2)
## Element Wise division 
print("Division:", arr1 / arr2)

Addition: [ 8 10 12 14 16 18]
Subtraction: [-6 -6 -6 -6 -6 -6]
Multiplication: [ 7 16 27 40 55 72]
Division: [0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]


In [ ]:
## 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr = np.arange(1,17).reshape(4,4)
sub = np.sum(arr,axis=1)
print(sub)




[10 26 42 58]


In [21]:
## 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

import numpy as np

arr = np.arange(1,26).reshape(5,5)
mean = np.mean(arr)
median = np.median(arr)
stan_devia = np.std(arr)
variance = np.var(arr)
print("Mean :",mean)
print("Median : ",median)
print("Standard Dviation :",stan_devia)
print("Variance : ",variance)

Mean : 13.0
Median :  13.0
Standard Dviation : 7.211102550927978
Variance :  52.0


In [24]:
## 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1)

import numpy as np
arr = np.arange(1,10).reshape(3,3)

mean = np.mean(arr)
stand_dev = np.std(arr)

normalize = (arr - mean )/ stan_devia
print(normalize)

[[-0.5547002  -0.41602515 -0.2773501 ]
 [-0.13867505  0.          0.13867505]
 [ 0.2773501   0.41602515  0.5547002 ]]


In [28]:
## 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


import numpy as np
arr = np.arange(1,10).reshape(3,3)
arr1 = np.array([3, 3, 3])
print(arr + arr1)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
## 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

import numpy as np
arr = np.arange(1,17).reshape(4,4)
arr1 = np.array([1,2,3,4]).reshape(4,1)
print(arr - arr1)



[[ 0  1  2  3]
 [ 3  4  5  6]
 [ 6  7  8  9]
 [ 9 10 11 12]]


In [53]:
## 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


import numpy as np
arr = np.arange(1,10).reshape(3,3)
det = np.linalg.det(arr)
eig_vig = np.linalg.eig(arr)
print(det)
print(eig_vig)

0.0
EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [52]:
arr = np.array([
    [3,2,4],
    [6,7,3],
    [9,3,7]
])
inv = np.linalg.inv(arr)
print(inv)

[[-0.44444444  0.02222222  0.24444444]
 [ 0.16666667  0.16666667 -0.16666667]
 [ 0.5        -0.1        -0.1       ]]


In [57]:
## 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
import numpy as np
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(1,7).reshape(3,2)
result = np.dot(arr1,arr2)
print(result)

[[22 28]
 [49 64]]


In [64]:
## 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

import numpy as np
arr = np.arange(1,10).reshape(3,3)
arr2 = np.reshape(arr,(1,9))
arr3 = np.reshape(arr,(9,1))
print(arr2)
print(arr3)


[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [4]:
## 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5)

import numpy as np
arr = np.arange(1,26).reshape(5,5)
flat = arr.flatten()
new_arr = flat.reshape(5,5)
print(flat)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [8]:
## 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

import numpy as np
arr = np.arange(1,26).reshape(5,5)
fancy = arr[[0,0,4,4],[0,4,0,4]] 
print(fancy)

[ 1  5 21 25]


In [ ]:
## 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10

import numpy as np
arr = np.arange(1,17).reshape(4,4)
